//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKButton.h"

@class NSString;

@interface ABKAppPurchaseButton : ABKButton
{
    _Bool _universal;
    float _price;
    NSString *_displayPrice;
}

@property(copy, nonatomic) NSString *displayPrice; // @synthesize displayPrice=_displayPrice;
@property(nonatomic) float price; // @synthesize price=_price;
@property(nonatomic) _Bool universal; // @synthesize universal=_universal;
- (void).cxx_destruct;
- (void)setPriceText:(id)arg1;
- (void)updateInsetsAndImage;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

