//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface ABKAttributionData : NSObject
{
    NSString *_network;
    NSString *_campaign;
    NSString *_adGroup;
    NSString *_creative;
}

@property(readonly, nonatomic) NSString *creative; // @synthesize creative=_creative;
@property(readonly, nonatomic) NSString *adGroup; // @synthesize adGroup=_adGroup;
@property(readonly, nonatomic) NSString *campaign; // @synthesize campaign=_campaign;
@property(readonly, nonatomic) NSString *network; // @synthesize network=_network;
- (void).cxx_destruct;
- (id)proxyForJson;
- (id)initWithNetwork:(id)arg1 campaign:(id)arg2 adGroup:(id)arg3 creative:(id)arg4;

@end

