//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKEvent.h"

@class NSString;

@interface ABKCustomStringAttributeEvent : ABKEvent
{
    NSString *_customAttributeKey;
    NSString *_value;
}

@property(copy) NSString *value; // @synthesize value=_value;
@property(copy) NSString *customAttributeKey; // @synthesize customAttributeKey=_customAttributeKey;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)getDataAsJson;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCustomAttributeKey:(id)arg1 value:(id)arg2;

@end

