//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface ABKCard : NSObject <NSCopying, NSCoding>
{
    _Bool _viewed;
    _Bool _openUrlInWebView;
    NSString *_idString;
    double _created;
    double _updated;
    unsigned long long _categories;
    double _expiresAt;
    NSDictionary *_extras;
    NSString *_urlString;
    NSString *_type;
}

+ (id)deserializeCardFromDictionary:(id)arg1;
+ (_Bool)cardDictionaryIsValid:(id)arg1 forType:(Class)arg2;
+ (_Bool)basicCardPropertiesAreValid:(id)arg1;
+ (_Bool)isValid:(id)arg1;
+ (Class)getClassForType:(id)arg1;
@property(copy) NSString *type; // @synthesize type=_type;
@property _Bool openUrlInWebView; // @synthesize openUrlInWebView=_openUrlInWebView;
@property(copy) NSString *urlString; // @synthesize urlString=_urlString;
@property(retain) NSDictionary *extras; // @synthesize extras=_extras;
@property double expiresAt; // @synthesize expiresAt=_expiresAt;
@property unsigned long long categories; // @synthesize categories=_categories;
@property(nonatomic) double updated; // @synthesize updated=_updated;
@property(nonatomic) double created; // @synthesize created=_created;
@property(nonatomic) _Bool viewed; // @synthesize viewed=_viewed;
@property(retain) NSString *idString; // @synthesize idString=_idString;
- (void).cxx_destruct;
- (void)logCardImpression;
- (void)logCardClicked;
- (id)serializeToData;
- (id)proxyForJson;
- (_Bool)hasSameId:(id)arg1;
- (void)setNilValueForKey:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)addCategory:(unsigned long long)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

