//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class ABKCardViewModel, ABKThemableCardBackgroundView, UIImageView;
@protocol ABKCardActionDelegate;

@interface ABKCardCell : UITableViewCell
{
    ABKThemableCardBackgroundView *_rootView;
    id <ABKCardActionDelegate> _actionDelegate;
    ABKCardViewModel *_cardViewModel;
    UIImageView *_readIndicator;
}

@property(retain, nonatomic) UIImageView *readIndicator; // @synthesize readIndicator=_readIndicator;
@property(retain) ABKCardViewModel *cardViewModel; // @synthesize cardViewModel=_cardViewModel;
@property __weak id <ABKCardActionDelegate> actionDelegate; // @synthesize actionDelegate=_actionDelegate;
@property(retain, nonatomic) ABKThemableCardBackgroundView *rootView; // @synthesize rootView=_rootView;
- (void).cxx_destruct;
- (void)disableUnreadIndicator:(_Bool)arg1;
- (void)setSubviews:(id)arg1 atCenterWithWidth:(double)arg2;
- (void)layoutSubviews;
- (id)reuseIdentifier;
- (void)awakeFromNib;

@end

