//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKCardCell.h"

@class ABKAppPurchaseButton, ABKLabel, ABKThemableCardSubtitleLabel, ABKThemableCardTabView, ABKThemableCardTitleLabel, ABKView, UIImageView, UILabel;

@interface ABKCrossPromotionCardCell : ABKCardCell
{
    ABKThemableCardTabView *_captionTab;
    UILabel *_caption;
    UIImageView *_tabImage;
    UIImageView *_cardImage;
    ABKThemableCardTitleLabel *_title;
    ABKThemableCardSubtitleLabel *_subtitle;
    ABKLabel *_reviews;
    ABKAppPurchaseButton *_button;
    ABKView *_starsAndSubtitleView;
}

@property(retain, nonatomic) ABKView *starsAndSubtitleView; // @synthesize starsAndSubtitleView=_starsAndSubtitleView;
@property(retain, nonatomic) ABKAppPurchaseButton *button; // @synthesize button=_button;
@property(retain, nonatomic) ABKLabel *reviews; // @synthesize reviews=_reviews;
@property(retain, nonatomic) ABKThemableCardSubtitleLabel *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) ABKThemableCardTitleLabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImageView *cardImage; // @synthesize cardImage=_cardImage;
@property(retain, nonatomic) UIImageView *tabImage; // @synthesize tabImage=_tabImage;
@property(retain, nonatomic) UILabel *caption; // @synthesize caption=_caption;
@property(retain, nonatomic) ABKThemableCardTabView *captionTab; // @synthesize captionTab=_captionTab;
- (void).cxx_destruct;
- (void)updateStarImages:(float)arg1;
- (void)layoutStarAndSubtitle;
- (void)layoutSubviews;
- (void)buttonPressed:(id)arg1;
- (void)layoutMajorSubviews;
- (void)awakeFromNib;

@end

