//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKCardViewModel.h"

@interface ABKCrossPromotionCardViewModel : ABKCardViewModel
{
    double _labelWidth;
    double _imageHeight;
    double _titleHeight;
    double _starsAndSubtitleBackgroundHeight;
    double _descriptionHeight;
    double _subtitleHeight;
    double _starsAndSubtitlePadding;
    double _starsAndSubtitleMinHeight;
}

+ (id)getStarImageWithKey:(id)arg1;
+ (id)fullStar;
+ (id)halfStar;
+ (id)emptyStar;
@property double starsAndSubtitleMinHeight; // @synthesize starsAndSubtitleMinHeight=_starsAndSubtitleMinHeight;
@property double starsAndSubtitlePadding; // @synthesize starsAndSubtitlePadding=_starsAndSubtitlePadding;
@property double subtitleHeight; // @synthesize subtitleHeight=_subtitleHeight;
@property double descriptionHeight; // @synthesize descriptionHeight=_descriptionHeight;
@property double starsAndSubtitleBackgroundHeight; // @synthesize starsAndSubtitleBackgroundHeight=_starsAndSubtitleBackgroundHeight;
@property double titleHeight; // @synthesize titleHeight=_titleHeight;
@property double imageHeight; // @synthesize imageHeight=_imageHeight;
@property double labelWidth; // @synthesize labelWidth=_labelWidth;
- (double)starsAndSubtitleViewHeight;
- (double)cardHeightWithWidth:(double)arg1;
- (void)associateWithCell:(id)arg1;

@end

