//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKPropertyTrigger.h"

@class NSString;

@interface ABKCustomEventPropertyTrigger : ABKPropertyTrigger
{
    NSString *_eventName;
}

@property(retain) NSString *eventName; // @synthesize eventName=_eventName;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)match:(id)arg1;
- (id)initWithEventName:(id)arg1 propertyFiltersJSON:(id)arg2;

@end

