//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class ABKCard, NSString;

@interface ABKCardViewModel : NSObject <NSCopying>
{
    _Bool _read;
    double _height;
    ABKCard *_card;
}

+ (double)getImageRatioWithCardImageRatio:(double)arg1 imageURLString:(id)arg2 defaultImageRatio:(double)arg3;
+ (id)viewModelFromCard:(id)arg1;
+ (void)initialize;
@property _Bool read; // @synthesize read=_read;
@property(retain) ABKCard *card; // @synthesize card=_card;
@property(nonatomic) double height; // @synthesize height=_height;
- (void).cxx_destruct;
- (_Bool)updateImageRatio:(double)arg1 fromOldRatio:(double)arg2 withCardRatio:(double)arg3;
- (double)cardHeightWithWidth:(double)arg1;
- (double)heightWithLimit:(double)arg1;
- (double)getHeightWithString:(id)arg1 font:(id)arg2 constraint:(struct CGSize)arg3 linkBreakMode:(long long)arg4;
- (double)getMultiLinesStaticLinkHeightWithWidth:(double)arg1 forString:(id)arg2;
- (double)getMultiLinesBodyLabelHeightWithWidth:(double)arg1 forString:(id)arg2;
- (double)getTitleHeightWithWidth:(double)arg1 forString:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)URLForCardClick;
- (void)resizeGradientTitleBackgroundView:(id)arg1 toFrame:(struct CGRect)arg2;
- (id)getCellClassName;
@property(readonly) NSString *cellReuseIdentifier;
@property(readonly) NSString *nibName;
- (void)associateWithCell:(id)arg1;
- (void)fetchImage:(id)arg1 intoView:(id)arg2 noImagePlaceholder:(id)arg3;
- (_Bool)updateImageRatio:(double)arg1;
- (id)imageURL;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithCard:(id)arg1;

@end

