//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKServerRequest.h"

@class ABKDevice, ABKEventLog, ABKFeedback, NSDictionary;

@interface ABKDataServerRequest : ABKServerRequest
{
    _Bool _shouldSendFullDeviceData;
    _Bool _isSessionStartRequest;
    unsigned long long _respondWithKeys;
    ABKEventLog *_eventLog;
    ABKDevice *_device;
    NSDictionary *_userAttributes;
    double _configLastUpdatedTime;
    ABKFeedback *_feedback;
}

@property _Bool isSessionStartRequest; // @synthesize isSessionStartRequest=_isSessionStartRequest;
@property _Bool shouldSendFullDeviceData; // @synthesize shouldSendFullDeviceData=_shouldSendFullDeviceData;
@property(retain) ABKFeedback *feedback; // @synthesize feedback=_feedback;
@property double configLastUpdatedTime; // @synthesize configLastUpdatedTime=_configLastUpdatedTime;
@property(retain) NSDictionary *userAttributes; // @synthesize userAttributes=_userAttributes;
@property(retain) ABKDevice *device; // @synthesize device=_device;
@property(retain) ABKEventLog *eventLog; // @synthesize eventLog=_eventLog;
@property unsigned long long respondWithKeys; // @synthesize respondWithKeys=_respondWithKeys;
- (void).cxx_destruct;
- (_Bool)isEmpty;
- (id)respondWithDictionary;
- (id)body;
- (void)setUserAttributesFromUserData:(id)arg1;
- (void)setRespondWithConfigFromUserData:(id)arg1;
- (void)populateFromUserData:(id)arg1;
- (id)endpointURL;
- (void)addRespondWithKeys:(unsigned long long)arg1;
- (_Bool)sendingFeedback;
- (_Bool)addFeedback:(id)arg1;
- (id)initWithUserId:(id)arg1 respondWithKeys:(unsigned long long)arg2;
- (id)initWithUserId:(id)arg1 feedback:(id)arg2;
- (id)initWithUserId:(id)arg1;

@end

