//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSDictionary;

@interface ABKFacebookUser : NSObject
{
    NSDictionary *_facebookUserDictionary;
    long long _numberOfFriends;
    NSArray *_likes;
}

@property(readonly) NSArray *likes; // @synthesize likes=_likes;
@property(readonly) long long numberOfFriends; // @synthesize numberOfFriends=_numberOfFriends;
@property(readonly) NSDictionary *facebookUserDictionary; // @synthesize facebookUserDictionary=_facebookUserDictionary;
- (void).cxx_destruct;
- (id)proxyForJson;
- (id)init;
- (id)initWithFacebookUserDictionary:(id)arg1 numberOfFriends:(long long)arg2 likes:(id)arg3;

@end

