//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface ABKFeedNoConnectionView : UIView
{
    UILabel *_noConnectionTitleLabel;
    UILabel *_noConnectionMessageLabel;
}

@property(retain, nonatomic) UILabel *noConnectionMessageLabel; // @synthesize noConnectionMessageLabel=_noConnectionMessageLabel;
@property(retain, nonatomic) UILabel *noConnectionTitleLabel; // @synthesize noConnectionTitleLabel=_noConnectionTitleLabel;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

