//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ABKCardActionDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ABKSpinnerView, NSMutableArray, NSMutableSet, NSString, UILabel, UIRefreshControl, UITableView, UIView;
@protocol ABKFeedViewControllerDelegate;

@interface ABKFeedViewController : UIViewController <ABKCardActionDelegate, UITableViewDataSource, UITableViewDelegate, SKStoreProductViewControllerDelegate>
{
    _Bool _disableUnreadIndicator;
    _Bool _viewIsDisplaying;
    double _cardWidthForiPhone;
    double _cardWidthForiPad;
    double _minimumCardMarginForiPhone;
    double _minimumCardMarginForiPad;
    id <ABKFeedViewControllerDelegate> _appboyDelegate;
    unsigned long long _categories;
    NSMutableArray *_currentViewModels;
    NSMutableSet *_viewedFeedItems;
    double _itemVerticalSpacing;
    UITableView *_tableView;
    ABKSpinnerView *_activityIndicatorView;
    UILabel *_emptyFeedLabel;
    UIView *_noConnectionView;
    NSMutableArray *_loadedCards;
    UIRefreshControl *_refreshControl;
}

@property(retain, nonatomic) UIRefreshControl *refreshControl; // @synthesize refreshControl=_refreshControl;
@property _Bool viewIsDisplaying; // @synthesize viewIsDisplaying=_viewIsDisplaying;
@property(retain) NSMutableArray *loadedCards; // @synthesize loadedCards=_loadedCards;
@property(retain, nonatomic) UIView *noConnectionView; // @synthesize noConnectionView=_noConnectionView;
@property(retain, nonatomic) UILabel *emptyFeedLabel; // @synthesize emptyFeedLabel=_emptyFeedLabel;
@property(retain, nonatomic) ABKSpinnerView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property double itemVerticalSpacing; // @synthesize itemVerticalSpacing=_itemVerticalSpacing;
@property(retain) NSMutableSet *viewedFeedItems; // @synthesize viewedFeedItems=_viewedFeedItems;
@property(retain) NSMutableArray *currentViewModels; // @synthesize currentViewModels=_currentViewModels;
@property(nonatomic) _Bool disableUnreadIndicator; // @synthesize disableUnreadIndicator=_disableUnreadIndicator;
@property(nonatomic) unsigned long long categories; // @synthesize categories=_categories;
@property __weak id <ABKFeedViewControllerDelegate> appboyDelegate; // @synthesize appboyDelegate=_appboyDelegate;
@property double minimumCardMarginForiPad; // @synthesize minimumCardMarginForiPad=_minimumCardMarginForiPad;
@property double minimumCardMarginForiPhone; // @synthesize minimumCardMarginForiPhone=_minimumCardMarginForiPhone;
@property double cardWidthForiPad; // @synthesize cardWidthForiPad=_cardWidthForiPad;
@property double cardWidthForiPhone; // @synthesize cardWidthForiPhone=_cardWidthForiPhone;
- (void).cxx_destruct;
- (void)loadSpinnerAndNoConnectionView;
- (void)viewDidUnload;
- (void)dealloc;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)productViewControllerSupported;
- (void)productViewControllerDidFinish:(id)arg1;
- (void)openItunesStoreProduct:(id)arg1;
- (void)openURLInWebView:(id)arg1;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)openCardURL:(id)arg1 inWebview:(_Bool)arg2;
- (_Bool)delegateHandlesCardURL:(id)arg1 withExtras:(id)arg2;
- (_Bool)delegateHandlesCardClick:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)getCellForViewModel:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)prepareToDisplayCards:(id)arg1;
- (void)feedUpdatedForDisplay:(id)arg1;
- (void)downloadCardsImagesIfNotCached:(id)arg1;
- (void)resetViewTrackingOfCards;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)receiveWillEnterForeground:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (double)calculateCardWidth;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)moveScrollIndicatorToRightSide;
- (void)resizeTableView;
- (void)viewDidLayoutSubviews;
- (void)updateCardImageRatio:(id)arg1;
- (void)refreshFeed;
- (void)viewDidLoad;
- (void)loadView;
- (void)setup;
- (id)init;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

