//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKEvent.h"

@class NSString;

@interface ABKGeofenceEvent : ABKEvent
{
    NSString *_geofenceId;
    long long _transitionType;
}

+ (id)convertTransitionTypeToString:(long long)arg1;
@property long long transitionType; // @synthesize transitionType=_transitionType;
@property(copy) NSString *geofenceId; // @synthesize geofenceId=_geofenceId;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)getDataAsJson;
- (id)getType;
- (id)initWithGeofenceId:(id)arg1 transitionType:(long long)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

