//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKServerRequest.h"

@class ABKLocationRecordedEvent;

@interface ABKGeofenceRefreshServerRequest : ABKServerRequest
{
    ABKLocationRecordedEvent *_locationRecordedEvent;
}

@property(retain) ABKLocationRecordedEvent *locationRecordedEvent; // @synthesize locationRecordedEvent=_locationRecordedEvent;
- (void).cxx_destruct;
- (id)body;
- (_Bool)isEmpty;
- (id)endpointURL;
- (id)initWithUserId:(id)arg1 locationRecordedEvent:(id)arg2;

@end

