//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKTriggeredAction.h"

@class ABKInAppMessage, ABKInAppMessageController;

@interface ABKInAppMessageTriggeredAction : ABKTriggeredAction
{
    ABKInAppMessage *_inAppMessage;
    ABKInAppMessageController *_inAppMessageController;
}

@property __weak ABKInAppMessageController *inAppMessageController; // @synthesize inAppMessageController=_inAppMessageController;
@property(retain) ABKInAppMessage *inAppMessage; // @synthesize inAppMessage=_inAppMessage;
- (void).cxx_destruct;
- (id)resourceLinks;
- (void)prefetchAssets;
- (id)inAppMessageZipFileURLString;
- (id)inAppMessageImageURLString;
- (void)displayTriggeredInAppMessage;
- (void)logControlGroupTriggerEvent;
- (void)performTriggeredAction:(id)arg1;

@end

