//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABKStack;
@protocol ABKInAppMessageControllerDelegate, ABKInAppMessageUIControlling;

@interface ABKInAppMessageController : NSObject
{
    id <ABKInAppMessageControllerDelegate> _delegate;
    id <ABKInAppMessageUIControlling> _inAppMessageUIController;
    ABKStack *_inAppMessageStack;
}

@property(retain) ABKStack *inAppMessageStack; // @synthesize inAppMessageStack=_inAppMessageStack;
@property(retain) id <ABKInAppMessageUIControlling> inAppMessageUIController; // @synthesize inAppMessageUIController=_inAppMessageUIController;
@property __weak id <ABKInAppMessageControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showInAppMessage:(id)arg1 fromTriggerAction:(id)arg2;
- (void)handleInAppMessageTrigger:(id)arg1;
- (id)getInAppMessageStack;
- (void)clearInAppMessageStack;
- (void)handleExistingInAppMessagesInQueueWithDelegate:(id)arg1;
- (void)addInAppMessage:(id)arg1;
- (long long)inAppMessagesRemainingOnStack;
- (void)displayNextInAppMessageWithDelegate:(id)arg1;
- (id)init;

@end

