//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString, NSURL, UIColor;

@interface ABKInAppMessage : NSObject
{
    _Bool _openUrlInWebView;
    _Bool _animateIn;
    _Bool _animateOut;
    _Bool _inAppMessageImpressionIsLogged;
    _Bool _inAppMessageClickedIsLogged;
    NSString *_message;
    NSDictionary *_extras;
    double _duration;
    long long _inAppMessageClickActionType;
    NSURL *_uri;
    long long _inAppMessageDismissType;
    UIColor *_backgroundColor;
    UIColor *_textColor;
    NSString *_icon;
    UIColor *_iconColor;
    UIColor *_iconBackgroundColor;
    NSURL *_imageURI;
    long long _imageContentMode;
    long long _orientation;
    long long _messageTextAlignment;
    NSString *_campaignId;
    NSString *_cardId;
    NSString *_triggerId;
}

+ (long long)getTextAlignmentBasedOnLayoutDirectionWithAlignmentValue:(id)arg1;
+ (id)getInAppMessageFromDictionary:(id)arg1;
+ (id)convertTextAlignTypeToString:(long long)arg1;
+ (id)convertImageCropTypeToString:(long long)arg1;
+ (id)convertOrientationTypeToString:(long long)arg1;
+ (id)convertClickActionTypeToString:(long long)arg1;
+ (void)saveColorAsHex:(id)arg1 withKey:(id)arg2 inDictionary:(id)arg3;
+ (long long)inAppMessageClickActionTypeFromString:(id)arg1 errorMessage:(id)arg2;
@property(copy) NSString *triggerId; // @synthesize triggerId=_triggerId;
@property _Bool inAppMessageClickedIsLogged; // @synthesize inAppMessageClickedIsLogged=_inAppMessageClickedIsLogged;
@property _Bool inAppMessageImpressionIsLogged; // @synthesize inAppMessageImpressionIsLogged=_inAppMessageImpressionIsLogged;
@property(copy) NSString *cardId; // @synthesize cardId=_cardId;
@property(copy) NSString *campaignId; // @synthesize campaignId=_campaignId;
@property _Bool animateOut; // @synthesize animateOut=_animateOut;
@property _Bool animateIn; // @synthesize animateIn=_animateIn;
@property long long messageTextAlignment; // @synthesize messageTextAlignment=_messageTextAlignment;
@property long long orientation; // @synthesize orientation=_orientation;
@property long long imageContentMode; // @synthesize imageContentMode=_imageContentMode;
@property(copy) NSURL *imageURI; // @synthesize imageURI=_imageURI;
@property(retain) UIColor *iconBackgroundColor; // @synthesize iconBackgroundColor=_iconBackgroundColor;
@property(retain) UIColor *iconColor; // @synthesize iconColor=_iconColor;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property long long inAppMessageDismissType; // @synthesize inAppMessageDismissType=_inAppMessageDismissType;
@property _Bool openUrlInWebView; // @synthesize openUrlInWebView=_openUrlInWebView;
@property(readonly) NSURL *uri; // @synthesize uri=_uri;
@property(readonly) long long inAppMessageClickActionType; // @synthesize inAppMessageClickActionType=_inAppMessageClickActionType;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(retain) NSDictionary *extras; // @synthesize extras=_extras;
@property(copy) NSString *message; // @synthesize message=_message;
- (void).cxx_destruct;
- (id)inAppMessageOrientationName:(long long)arg1;
- (void)setInAppMessageClickAction:(long long)arg1 withURI:(id)arg2;
- (void)logInAppMessageClicked;
- (void)logInAppMessageImpression;
- (id)proxyForJson;
- (id)serializeToData;
- (id)description;
- (void)setNilValueForKey:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)init;

@end

