//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKEvent.h"

@class NSString;

@interface ABKInAppMessageButtonClickedEvent : ABKEvent
{
    NSString *_inAppMessageButtonClickedCardId;
    NSString *_inAppMessageButtonClickedCampaignId;
    NSString *_inAppMessageButtonClickedButtonId;
    NSString *_inAppMessageTriggerId;
}

@property(copy) NSString *inAppMessageTriggerId; // @synthesize inAppMessageTriggerId=_inAppMessageTriggerId;
@property(copy) NSString *inAppMessageButtonClickedButtonId; // @synthesize inAppMessageButtonClickedButtonId=_inAppMessageButtonClickedButtonId;
@property(copy) NSString *inAppMessageButtonClickedCampaignId; // @synthesize inAppMessageButtonClickedCampaignId=_inAppMessageButtonClickedCampaignId;
@property(copy) NSString *inAppMessageButtonClickedCardId; // @synthesize inAppMessageButtonClickedCardId=_inAppMessageButtonClickedCardId;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)getDataAsJson;
- (id)getType;
- (id)initWithCardId:(id)arg1 campaignId:(id)arg2 buttonId:(id)arg3 triggerId:(id)arg4;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

