//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKEvent.h"

@class NSString;

@interface ABKInAppMessageClickEvent : ABKEvent
{
    NSString *_clickedInAppMessageCardId;
    NSString *_clickedInAppMessageCampaignId;
    NSString *_clickedInAppMessageTriggerId;
}

@property(copy) NSString *clickedInAppMessageTriggerId; // @synthesize clickedInAppMessageTriggerId=_clickedInAppMessageTriggerId;
@property(copy) NSString *clickedInAppMessageCampaignId; // @synthesize clickedInAppMessageCampaignId=_clickedInAppMessageCampaignId;
@property(copy) NSString *clickedInAppMessageCardId; // @synthesize clickedInAppMessageCardId=_clickedInAppMessageCardId;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)getDataAsJson;
- (id)getType;
- (id)initWithCardId:(id)arg1 campaignId:(id)arg2 triggerId:(id)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

