//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ABKLocationUtilities : NSObject
{
}

+ (_Bool)locationIsValidWithLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(double)arg3 altitude:(double)arg4 verticalAccuracy:(double)arg5;
+ (_Bool)locationIsValidWithLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(double)arg3;
+ (id)buildLocationWithLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(double)arg3 altitude:(double)arg4 verticalAccuracy:(double)arg5;
+ (id)buildLocationWithLatitude:(double)arg1 longitude:(double)arg2 horizontalAccuracy:(double)arg3;
+ (_Bool)isValidLocationAndAccurateEnough:(id)arg1;
+ (_Bool)isLocationLinkedAndEnabled;
+ (_Bool)isCoreLocationLinked;
+ (Class)getCircularRegionClass;
+ (Class)getLocationClass;
+ (Class)getLocationManagerClass;

@end

