//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABKGeofenceManager, ABKSignificantChangeLocationProvider, ABKSinglePointLocationProvider;

@interface ABKLocationManager : NSObject
{
    _Bool _disableLocationTracking;
    ABKSignificantChangeLocationProvider *_significantChangeProvider;
    ABKSinglePointLocationProvider *_singlePointLocationProvider;
    ABKGeofenceManager *_geofenceManager;
}

@property(retain) ABKGeofenceManager *geofenceManager; // @synthesize geofenceManager=_geofenceManager;
@property(retain) ABKSinglePointLocationProvider *singlePointLocationProvider; // @synthesize singlePointLocationProvider=_singlePointLocationProvider;
@property(retain) ABKSignificantChangeLocationProvider *significantChangeProvider; // @synthesize significantChangeProvider=_significantChangeProvider;
@property(readonly) _Bool disableLocationTracking; // @synthesize disableLocationTracking=_disableLocationTracking;
- (void).cxx_destruct;
- (id)lastGeofenceUpdate;
- (void)requestGeofences;
- (void)registerGeofences:(id)arg1;
- (void)requestSingleLocationAndLogLocationEvent:(_Bool)arg1;
- (void)allowRequestAlwaysPermission;
- (void)allowRequestWhenInUseLocationPermission;
- (void)logSingleLocation;
- (id)initWithServerConfig:(id)arg1 appboyOptions:(id)arg2 appboyManager:(id)arg3;

@end

