//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKCardViewModel.h"

@interface ABKNewsCardViewModel : ABKCardViewModel
{
    double _imageHeight;
    double _labelWidth;
    double _titleHeight;
    double _descriptionHeight;
    double _linkHeight;
}

@property double linkHeight; // @synthesize linkHeight=_linkHeight;
@property double descriptionHeight; // @synthesize descriptionHeight=_descriptionHeight;
@property double titleHeight; // @synthesize titleHeight=_titleHeight;
@property double labelWidth; // @synthesize labelWidth=_labelWidth;
@property double imageHeight; // @synthesize imageHeight=_imageHeight;
- (double)cardHeightWithWidth:(double)arg1;
- (void)associateWithCell:(id)arg1;

@end

