//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ABKNotificationCenter : NSObject
{
}

+ (id)defaultCenter;
- (void)postDeviceInfoChanged;
- (void)addObserver:(id)arg1 forChangeOnDevice:(SEL)arg2;
- (id)getTriggersFromServerFromNotification:(id)arg1;
- (void)postTriggersReceivedFromServer:(id)arg1;
- (void)addObserver:(id)arg1 forTriggersFromServer:(SEL)arg2;
- (void)removeObserverForTriggerRequestFailed:(id)arg1;
- (void)postTriggerRequestFailedNotification;
- (void)addObserver:(id)arg1 forTriggerRequestFailed:(SEL)arg2;
- (void)removeObserverForTrigger:(id)arg1;
- (id)getTriggerEventFromNotification:(id)arg1;
- (void)postTriggerNotificationWithType:(id)arg1 data:(id)arg2;
- (void)postIAMClickTriggerNotificationWithButtonClickEvent:(id)arg1;
- (void)postIAMClickTriggerNotificationWithBodyClickEvent:(id)arg1;
- (void)postTestTriggerNotification;
- (void)postPushClickTriggerNotificationWithPushClickEvent:(id)arg1;
- (void)postPurchaseTriggerNotificationWithPurchase:(id)arg1;
- (void)postOpenAppTriggerNotification;
- (void)postCustomEventTriggerNotificationWithCustomEvent:(id)arg1;
- (void)addObserver:(id)arg1 forTrigger:(SEL)arg2;
- (void)postFeedUpdatedNotificationWithSuccessful:(_Bool)arg1;
- (id)cardFromCardGeneratedImpressionNotification:(id)arg1;
- (void)postCardGeneratedImpression:(id)arg1;
- (void)addObserver:(id)arg1 forCardGeneratedImpression:(SEL)arg2;
- (void)removeObserverForEventForDataFlush:(id)arg1;
- (id)getEventForDataFlushFromNotification:(id)arg1;
- (void)postEventForDataFlush:(id)arg1;
- (void)addObserver:(id)arg1 forEventForDataFlush:(SEL)arg2;
- (_Bool)wasFeedbackSentSuccessfullyFromNotification:(id)arg1;
- (void)postSentFeedbackNotification:(_Bool)arg1;
- (id)getExceptionFromNotification:(id)arg1;
- (void)postLogExceptionNotificationWithName:(id)arg1 reason:(id)arg2 inMethodName:(id)arg3;
- (void)postLogExceptionNotification:(id)arg1 inMethodName:(id)arg2;
- (void)addObserver:(id)arg1 toLogException:(SEL)arg2;
- (void)addObserver:(id)arg1 forServerRequestComplete:(SEL)arg2;
- (void)postServerRequestComplete;
- (id)getSingleLocationFromNotification:(id)arg1;
- (void)postSingleLocationLoggedNotification:(id)arg1;
- (void)addObserver:(id)arg1 forSingleLocationPointLogged:(SEL)arg2;
- (id)getSingleLocationEventProvidedFromNotification:(id)arg1;
- (void)postSingleLocationEventProvidedNotification:(id)arg1;
- (void)addObserver:(id)arg1 forSingleLocationEventProvided:(SEL)arg2;
- (id)getUpdatedServerGeofencesConfigFromNotification:(id)arg1;
- (void)postServerGeofencesConfigUpdatedNotification:(id)arg1;
- (void)addObserver:(id)arg1 forGeofencesServerConfigUpdated:(SEL)arg2;
- (id)getUpdatedServerLocationConfigFromNotification:(id)arg1;
- (void)postServerLocationConfigUpdatedNotification:(id)arg1;
- (void)addObserver:(id)arg1 forServerLocationConfigUpdated:(SEL)arg2;
- (id)addObserverForName:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)removeObserver:(id)arg1 name:(id)arg2;
- (id)getObjectFromNotification:(id)arg1 notificationName:(id)arg2 inClass:(Class)arg3;
- (void)postNotificationName:(id)arg1 objectForUserInfo:(id)arg2;
- (void)addObserver:(id)arg1 forName:(id)arg2 withSelector:(SEL)arg3;
- (void)removeObserver:(id)arg1;

@end

