//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ABKNUISettingOrDefault : NSObject
{
}

+ (id)getNuiRendererClass;
+ (id)getNuiSettingsClass;
+ (id)settingOrDefaultForFontWithFontValue:(id)arg1 nuiClassName:(id)arg2;
+ (id)settingOrDefaultForStringProperty:(id)arg1 defaultValue:(id)arg2 nuiClassName:(id)arg3;
+ (id)settingOrDefaultForImageProperty:(id)arg1 defaultValue:(id)arg2 nuiClassName:(id)arg3;
+ (id)settingOrDefaultForColorProperty:(id)arg1 defaultValue:(id)arg2 nuiClassName:(id)arg3;
+ (float)settingOrDefaultForFloatProperty:(id)arg1 defaultValue:(float)arg2 nuiClassName:(id)arg3;

@end

