//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABKManager, ABKTriggerManager, NSString;

@interface ABKPushNotificationManager : NSObject
{
    ABKManager *_manager;
    ABKTriggerManager *_triggerManager;
    NSString *_pushStoryAppGroup;
}

@property(copy, nonatomic) NSString *pushStoryAppGroup; // @synthesize pushStoryAppGroup=_pushStoryAppGroup;
@property(nonatomic) __weak ABKTriggerManager *triggerManager; // @synthesize triggerManager=_triggerManager;
@property(nonatomic) __weak ABKManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)handleNotificationResponse:(id)arg1 actionIdentifier:(id)arg2 URLDelegate:(id)arg3 pushURIDelegate:(id)arg4;
- (_Bool)isPushStoryClick:(id)arg1 identifier:(id)arg2;
- (void)handlePushStoryClick:(id)arg1 identifier:(id)arg2 URLDelegate:(id)arg3 pushURIDelegate:(id)arg4;
- (id)getStoredPushStoryDictionaryForCampaignId:(id)arg1;
- (id)getCampaignIdForFetchingStoredPushStory:(id)arg1;
- (void)removeStoredPushStoryInfoWithCampaignId:(id)arg1;
- (id)getStoredPushStoryDismissedTimeWithCampaignId:(id)arg1;
- (id)getStoredPushStoryPageIdWithCampaignId:(id)arg1;
- (id)getNotificationContentWithPushStoryPayload:(id)arg1;
- (void)createLocalPushWithPushStoryPayload:(id)arg1;
- (void)postPushStoryInternalErrorName:(id)arg1 reason:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)downloadPushStoryImages:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)handleSilentPushStoryNotification:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)waitForGeofenceUpdateWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)openPushURLWithSystem:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)openPushURLInWebView:(id)arg1;
- (_Bool)openPushURLString:(id)arg1 inWebView:(_Bool)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (_Bool)pushURLHandledByURLDelegate:(id)arg1 pushURIDelegate:(id)arg2 URLString:(id)arg3 pushPayload:(id)arg4;
- (void)clearBadgeCount;
- (void)fetchTestTriggersIfAvailable:(_Bool)arg1;
- (void)handlePushButtonClick:(id)arg1 identifier:(id)arg2 withURLDelegate:(id)arg3 withPushURIDelegate:(id)arg4 applicationState:(long long)arg5;
- (_Bool)handlePushBodyClick:(id)arg1 withURLDelegate:(id)arg2 withPushURIDelegate:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)pushReceivedInForeground:(id)arg1;
- (id)initWithAppboyManager:(id)arg1 triggerManager:(id)arg2;

@end

