//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABKPersistentData, NSString;

@interface ABKPlaceIQManager : NSObject
{
    _Bool _hasRun;
    ABKPersistentData *_persistentUserData;
    NSString *_deviceIdForRequest;
}

+ (void)queuePlaceIQIdRequest;
@property _Bool hasRun; // @synthesize hasRun=_hasRun;
@property(retain) NSString *deviceIdForRequest; // @synthesize deviceIdForRequest=_deviceIdForRequest;
@property(retain) ABKPersistentData *persistentUserData; // @synthesize persistentUserData=_persistentUserData;
- (void).cxx_destruct;
- (void)processReturnPlaceIQData:(id)arg1;
- (id)getRequestWithDeviceId:(id)arg1;
- (void)startConnectionWithRequest:(id)arg1;
- (void)requestPlaceIQId;
- (void)clearQueuedPlaceIQIdRequest;
- (_Bool)hasQueuedPlaceIQIdRequest;
- (void)requestPlaceIQIdIfApplicable;
- (id)initWithpersistentData:(id)arg1;

@end

