//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKEvent.h"

@class NSString;

@interface ABKPushStoryClickEvent : ABKEvent
{
    NSString *_campaignId;
    NSString *_pageId;
}

@property(copy) NSString *pageId; // @synthesize pageId=_pageId;
@property(copy) NSString *campaignId; // @synthesize campaignId=_campaignId;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)getDataAsJson;
- (id)getType;
- (id)initWithCampaignId:(id)arg1 pageId:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

