//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKTrigger.h"

@class NSString;

@interface ABKPushClickTrigger : ABKTrigger
{
    NSString *_campaignId;
}

+ (id)deCodeCampaignIdFromPushCId:(id)arg1;
@property(retain) NSString *campaignId; // @synthesize campaignId=_campaignId;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)match:(id)arg1;
- (id)initWithCampaignId:(id)arg1;

@end

