//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABKPersistentData, ABKReachability, ABKRequestQueue, ABKService;

@interface ABKRequestDispatcher : NSObject
{
    ABKReachability *_reachability;
    _Bool _requestInProgress;
    ABKRequestQueue *_requestQueue;
    ABKService *_service;
    ABKPersistentData *_persistentData;
}

@property(retain) ABKPersistentData *persistentData; // @synthesize persistentData=_persistentData;
@property(retain) ABKService *service; // @synthesize service=_service;
@property(retain) ABKRequestQueue *requestQueue; // @synthesize requestQueue=_requestQueue;
@property _Bool requestInProgress; // @synthesize requestInProgress=_requestInProgress;
- (void).cxx_destruct;
- (void)dealloc;
- (void)handleFailedDataRequest:(id)arg1;
- (void)onConnectionStatusChange:(id)arg1;
- (void)consumeQueueIfWeHaveInternetConnectivity;
- (_Bool)isNetworkRequestRequired;
- (_Bool)populatedRequestIsEmpty:(id)arg1;
- (_Bool)deviceIdentifierIsValid;
- (void)consume;
- (void)requestCompleted:(id)arg1;
- (void)addRequestToFrontOfQueue:(id)arg1;
- (void)addRequestToQueue:(id)arg1;
- (id)templateRequestWithTriggerEvent:(id)arg1 triggerAction:(id)arg2;
- (id)geofenceRequestWithGeofenceEvent:(id)arg1;
- (id)geofenceRequestWithLocationRecordedEvent:(id)arg1;
- (id)dataRequestWithRespondWithKeys:(unsigned long long)arg1;
- (id)dataRequestWithFeedback:(id)arg1;
- (void)markDataRequestAsSessionStartRequest:(id)arg1;
- (void)sendFullDeviceInfoWithDataRequest:(id)arg1;
- (id)initWithPersistentUserData:(id)arg1 service:(id)arg2;

@end

