//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class ABKGeofencesServerConfig, ABKLocationServerConfig, NSArray;

@interface ABKServerConfig : NSObject <NSCoding>
{
    double _configUpdateTime;
    NSArray *_eventsBlacklist;
    NSArray *_attributesBlacklist;
    NSArray *_purchasesBlacklist;
    ABKLocationServerConfig *_locationConfig;
    ABKGeofencesServerConfig *_geofencesConfig;
    double _messagingSessionTimeout;
}

@property double messagingSessionTimeout; // @synthesize messagingSessionTimeout=_messagingSessionTimeout;
@property(retain) ABKGeofencesServerConfig *geofencesConfig; // @synthesize geofencesConfig=_geofencesConfig;
@property(retain) ABKLocationServerConfig *locationConfig; // @synthesize locationConfig=_locationConfig;
@property(retain) NSArray *purchasesBlacklist; // @synthesize purchasesBlacklist=_purchasesBlacklist;
@property(retain) NSArray *attributesBlacklist; // @synthesize attributesBlacklist=_attributesBlacklist;
@property(retain) NSArray *eventsBlacklist; // @synthesize eventsBlacklist=_eventsBlacklist;
@property double configUpdateTime; // @synthesize configUpdateTime=_configUpdateTime;
- (void).cxx_destruct;
- (_Bool)purchasesBlacklistContainsKey:(id)arg1;
- (_Bool)attributesBlacklistContainsKey:(id)arg1;
- (_Bool)eventsBlacklistContainsKey:(id)arg1;
- (_Bool)doesBlacklist:(id)arg1 containKey:(id)arg2;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)setNilValueForKey:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

