//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface ABKSpinnerView : UIView
{
    UIView *_spinnerBackground;
}

@property(retain, nonatomic) UIView *spinnerBackground; // @synthesize spinnerBackground=_spinnerBackground;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

