//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKNavigationBar.h"

@interface ABKThemableFeedNavigationBar : ABKNavigationBar
{
    _Bool _isThemable;
}

@property _Bool isThemable; // @synthesize isThemable=_isThemable;
- (id)getNuiRendererClass;
- (void)dealloc;
- (void)checkAndApplyNUITheming;

@end

