//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@interface ABKTrigger : NSObject <NSCoding>
{
}

+ (id)getTriggerConditionFromDictionary:(id)arg1 withKey:(id)arg2;
+ (id)getTriggerFromDictionary:(id)arg1;
- (_Bool)match:(id)arg1;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

