//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKInAppMessageTriggeredAction.h"

@class ABKManager;

@interface ABKTemplatedIAMTriggeredAction : ABKInAppMessageTriggeredAction
{
    ABKManager *_manager;
}

@property(retain) ABKManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (id)inAppMessageZipFileURLString;
- (id)inAppMessageImageURLString;
- (id)resourceLinks;
- (void)performTriggeredAction:(id)arg1;
- (void)prefetchAssets;

@end

