//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ABKInAppMessageController, ABKManager, ABKPersistentData, ABKPushNotificationTrackEvent, ABKTriggerAssetManager, NSArray, NSDate, NSMutableSet, NSOperationQueue;

@interface ABKTriggerManager : NSObject
{
    _Bool _openAppTriggeredForCurrentSession;
    _Bool _pushClickAwaitingTriggersRefresh;
    ABKPersistentData *_persistentData;
    NSArray *_triggerActions;
    ABKTriggerAssetManager *_assetManager;
    ABKInAppMessageController *_inAppMessageController;
    double _triggerTimeInterval;
    NSDate *_lastTriggerTime;
    ABKManager *_appboyManager;
    NSOperationQueue *_triggerSerialOperationQueue;
    NSMutableSet *_triggeredActionSet;
    NSObject *_pendingPushClickTriggerLock;
    ABKPushNotificationTrackEvent *_pushTriggerAwaitingRefreshPushClickEvent;
}

@property(retain) ABKPushNotificationTrackEvent *pushTriggerAwaitingRefreshPushClickEvent; // @synthesize pushTriggerAwaitingRefreshPushClickEvent=_pushTriggerAwaitingRefreshPushClickEvent;
@property _Bool pushClickAwaitingTriggersRefresh; // @synthesize pushClickAwaitingTriggersRefresh=_pushClickAwaitingTriggersRefresh;
@property(retain) NSObject *pendingPushClickTriggerLock; // @synthesize pendingPushClickTriggerLock=_pendingPushClickTriggerLock;
@property(retain) NSMutableSet *triggeredActionSet; // @synthesize triggeredActionSet=_triggeredActionSet;
@property(retain) NSOperationQueue *triggerSerialOperationQueue; // @synthesize triggerSerialOperationQueue=_triggerSerialOperationQueue;
@property(retain) ABKManager *appboyManager; // @synthesize appboyManager=_appboyManager;
@property(retain) NSDate *lastTriggerTime; // @synthesize lastTriggerTime=_lastTriggerTime;
@property double triggerTimeInterval; // @synthesize triggerTimeInterval=_triggerTimeInterval;
@property _Bool openAppTriggeredForCurrentSession; // @synthesize openAppTriggeredForCurrentSession=_openAppTriggeredForCurrentSession;
@property(retain) ABKInAppMessageController *inAppMessageController; // @synthesize inAppMessageController=_inAppMessageController;
@property(retain) ABKTriggerAssetManager *assetManager; // @synthesize assetManager=_assetManager;
@property(retain) NSArray *triggerActions; // @synthesize triggerActions=_triggerActions;
@property(retain) ABKPersistentData *persistentData; // @synthesize persistentData=_persistentData;
- (void).cxx_destruct;
- (_Bool)withinMinTimeSinceLastTrigger:(id)arg1;
- (void)synchronizeTriggerActionsToUserDefaults;
- (void)resetOpenAppTriggeredForCurrentSession;
- (void)clearExistingTriggers;
- (void)dealloc;
- (id)getBestMatchingTriggerAction:(id)arg1;
- (void)handleTriggerFromNotification:(id)arg1;
- (void)reportAnyPendingPushClickTrigger;
- (void)setPendingPushClickWithEvent:(id)arg1;
- (void)triggerRequestFailed:(id)arg1;
- (void)receiveTriggersFromNotification:(id)arg1;
- (id)initWithPersistentData:(id)arg1 appboyManager:(id)arg2 inAppMessageController:(id)arg3 appboyOptions:(id)arg4;

@end

