//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABKView.h"

@class CAGradientLayer, CALayer;

@interface ABKThemableCardTitleBackgroundView : ABKView
{
    _Bool _isThemable;
    CAGradientLayer *_gradientLayer;
    CALayer *_topLine;
    CALayer *_bottomLine;
}

@property(retain) CALayer *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain) CALayer *topLine; // @synthesize topLine=_topLine;
@property(retain) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property _Bool isThemable; // @synthesize isThemable=_isThemable;
- (void).cxx_destruct;
- (void)drawBorderLines;
- (id)solidOnePixelLineWidth:(double)arg1;
- (void)drawBackgroundGradient;
- (void)drawGradientAndBorder;
- (void)layoutSubviews;
- (void)checkAndApplyNUITheming;

@end

