//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface ABKTwitterUser : NSObject
{
    NSString *_userDescription;
    NSString *_twitterName;
    NSString *_profileImageUrl;
    NSString *_screenName;
    long long _followersCount;
    long long _friendsCount;
    long long _statusesCount;
    long long _twitterID;
}

@property long long twitterID; // @synthesize twitterID=_twitterID;
@property long long statusesCount; // @synthesize statusesCount=_statusesCount;
@property long long friendsCount; // @synthesize friendsCount=_friendsCount;
@property long long followersCount; // @synthesize followersCount=_followersCount;
@property(copy) NSString *screenName; // @synthesize screenName=_screenName;
@property(copy) NSString *profileImageUrl; // @synthesize profileImageUrl=_profileImageUrl;
@property(copy) NSString *twitterName; // @synthesize twitterName=_twitterName;
@property(copy) NSString *userDescription; // @synthesize userDescription=_userDescription;
- (void).cxx_destruct;
- (id)proxyForJson;
- (id)init;

@end

