//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ABKViewUtilities : NSObject
{
}

+ (id)fetchImageIfCached:(id)arg1;
+ (void)stackViews:(id)arg1 startYPosition:(double)arg2 padding:(double)arg3 spacing:(double)arg4 maxTotalHeight:(double)arg5;
+ (void)setViewCenterX:(id)arg1 centerX:(double)arg2;
+ (void)setViewCenterY:(id)arg1 centerY:(double)arg2;
+ (void)setViewWidth:(id)arg1 width:(double)arg2;
+ (void)setViewHeight:(id)arg1 height:(double)arg2;
+ (void)setViewOriginX:(id)arg1 originX:(double)arg2;
+ (void)setViewOriginY:(id)arg1 originY:(double)arg2;

@end

