//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface ABKZipDownloadManager : NSObject
{
    _Bool _isDownloading;
    CDUnknownBlockType _completionHandler;
    NSString *_localPathString;
    NSString *_localPathOfZipFile;
}

@property _Bool isDownloading; // @synthesize isDownloading=_isDownloading;
@property(retain) NSString *localPathOfZipFile; // @synthesize localPathOfZipFile=_localPathOfZipFile;
@property(retain) NSString *localPathString; // @synthesize localPathString=_localPathString;
@property(copy) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (void).cxx_destruct;
- (void)unzipDownloadedFileAndCallCompletionHandler;
- (void)saveZipFileFromData:(id)arg1;
- (_Bool)downloadFileFromRemoteURL:(id)arg1 to:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;

@end

