//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface AKFFacebookAppEventsUtility : NSObject
{
}

+ (_Bool)facebookAppEventsEnabled;
+ (void)_logToFBAppEvents:(id)arg1 parameters:(id)arg2;
+ (void)logEvent:(id)arg1 parameters:(id)arg2;
+ (id)_eventNameMap;

@end

