//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AKFContentViewController.h"

#import "AKFConfiguring-Protocol.h"
#import "AKFCountryCodeTableViewControllerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class AKFCountry, AKFInputView, AKFKeyboardObserver, AKFPhoneNumber, NSArray, NSString, UILabel, UIView;
@protocol AKFPhoneLoginViewControllerDelegate;

@interface AKFPhoneLoginViewController : AKFContentViewController <AKFCountryCodeTableViewControllerDelegate, UITextFieldDelegate, AKFConfiguring>
{
    unsigned long long _buttonType;
    NSArray *_countries;
    AKFCountry *_country;
    AKFInputView *_countryCodeView;
    UILabel *_countryDialingCodeLabel;
    AKFInputView *_phoneNumberView;
    AKFKeyboardObserver *_keyboardObserver;
    UIView *_nextButtonWrapper;
    _Bool _wasNextButtonOutOfBounds;
    _Bool _enableSendToFacebook;
    _Bool _retry;
    NSArray *_blacklistedCountryCodes;
    NSString *_defaultCountryCode;
    NSArray *_whitelistedCountryCodes;
    id <AKFPhoneLoginViewControllerDelegate> _delegate;
    AKFPhoneNumber *_initialPhoneNumber;
}

@property(nonatomic, getter=isRetry) _Bool retry; // @synthesize retry=_retry;
@property(copy, nonatomic) AKFPhoneNumber *initialPhoneNumber; // @synthesize initialPhoneNumber=_initialPhoneNumber;
@property(nonatomic) __weak id <AKFPhoneLoginViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSArray *whitelistedCountryCodes; // @synthesize whitelistedCountryCodes=_whitelistedCountryCodes;
@property(nonatomic) _Bool enableSendToFacebook; // @synthesize enableSendToFacebook=_enableSendToFacebook;
@property(copy, nonatomic) NSString *defaultCountryCode; // @synthesize defaultCountryCode=_defaultCountryCode;
@property(copy, nonatomic) NSArray *blacklistedCountryCodes; // @synthesize blacklistedCountryCodes=_blacklistedCountryCodes;
- (void).cxx_destruct;
- (void)_updateStrings;
- (void)_updatePhoneNumberText:(id)arg1;
- (void)_updateNextButtonForText:(id)arg1;
- (void)_updateCountry:(id)arg1;
- (void)_snapNextButtonAboveKeyboard;
- (_Bool)_shouldSnapNextButtonAboveKeyboard;
- (void)_openCountryCodeView:(id)arg1;
- (double)_defaultBodyViewHeight;
- (id)_currentPhoneNumber;
- (id)_countryDialingCodeText;
- (id)scrollViewAboveKeyboardConstraint;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)countryCodeTableViewController:(id)arg1 didSelectCountry:(id)arg2;
- (id)defaultTextField;
- (void)next:(id)arg1;
- (void)applyTheme:(id)arg1;
- (void)keyboardObserverWillShowKeyboard:(id)arg1;
- (void)keyboardObserverWillHideKeyboard:(id)arg1;
- (void)loadAdvancedUI;
- (id)defaultBodyView;
- (void)addViewConstraints;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (unsigned long long)loginFlowState;
- (id)appEventViewName;
- (id)appEventNextButtonType;
- (id)appEventExtras;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

