//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface AKFSettings : NSObject
{
}

+ (void)setAccountKitFacebookAppEventsEnabled:(id)arg1;
+ (id)accountKitFacebookAppEventsEnabled;
+ (void)setClientToken:(id)arg1;
+ (id)clientToken;
+ (void)setAppID:(id)arg1;
+ (id)appID;
+ (void)setAppName:(id)arg1;
+ (id)appName;

@end

