//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AKFContainerViewController.h"

#import "AKFTheming-Protocol.h"

@class AKFAppEventsLogger, AKFTheme, NSDictionary, NSString, UIImageView, UIView;

@interface AKFViewControllerBase : AKFContainerViewController <AKFTheming>
{
    UIView *_backgroundColorView;
    UIImageView *_backgroundImageView;
    _Bool _didAddTapGestureRecognizer;
    AKFTheme *_theme;
    AKFAppEventsLogger *_appEventsLogger;
    unsigned long long _loginType;
}

@property(readonly, nonatomic) unsigned long long loginType; // @synthesize loginType=_loginType;
@property(readonly, nonatomic) AKFAppEventsLogger *appEventsLogger; // @synthesize appEventsLogger=_appEventsLogger;
- (void).cxx_destruct;
- (void)_updateToolbarTitleWithTheme:(id)arg1;
- (void)_updateContentViewWithTheme:(id)arg1;
- (void)_tapHandler:(id)arg1;
- (void)_addViewConstraintsToFillViews:(id)arg1;
@property(copy, nonatomic) AKFTheme *theme;
- (void)keyboardObserverWillShowKeyboard:(id)arg1;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)applyTheme:(id)arg1;
- (void)addViewConstraints;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(readonly, copy, nonatomic) NSString *appEventViewName;
@property(readonly, copy, nonatomic) NSDictionary *appEventExtras;
- (id)initWithAppEventsLogger:(id)arg1 loginType:(unsigned long long)arg2;

@end

