//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BFTask;

@interface BFTaskCompletionSource : NSObject
{
    BFTask *_task;
}

+ (id)taskCompletionSource;
@property(readonly, nonatomic) BFTask *task; // @synthesize task=_task;
- (void).cxx_destruct;
- (_Bool)trySetCancelled;
- (_Bool)trySetException:(id)arg1;
- (_Bool)trySetError:(id)arg1;
- (_Bool)trySetResult:(id)arg1;
- (void)cancel;
- (void)setException:(id)arg1;
- (void)setError:(id)arg1;
- (void)setResult:(id)arg1;
- (id)init;

@end

