//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CLSThreadArrayOperation.h"

@class CLSSymbolResolver;

@interface CLSSymbolicationOperation : CLSThreadArrayOperation
{
    CLSSymbolResolver *_symbolResolver;
}

@property(retain, nonatomic) CLSSymbolResolver *symbolResolver; // @synthesize symbolResolver=_symbolResolver;
- (void).cxx_destruct;
- (void)main;

@end

