//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AVPlayerItemLegibleOutputPushDelegate-Protocol.h"

@class NSString;

@interface FAVPlayerItemLegibleOutputPushDelegate : NSObject <AVPlayerItemLegibleOutputPushDelegate>
{
    struct FAvfMediaTracks *Tracks;
}

- (void)legibleOutput:(id)arg1 didOutputAttributedStrings:(id)arg2 nativeSampleBuffers:(id)arg3 forItemTime:(CDStruct_1b6d18a9)arg4;
- (id)initWithMediaTracks:(struct FAvfMediaTracks *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

