//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBAdSafariViewController : NSObject
{
}

+ (void)presentSafariViewControllerWithURL:(id)arg1 withRootViewController:(id)arg2 withDelegate:(id)arg3;
+ (_Bool)supportsWebKit;
+ (_Bool)supportsSafariServices;

@end

