//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBAdLogger : NSObject
{
}

+ (id)levelAsString:(int)arg1;
+ (void)logInTestModeWithFile:(const char *)arg1 lineNumber:(int)arg2 format:(id)arg3;
+ (void)logAtLevel:(int)arg1 file:(const char *)arg2 lineNumber:(int)arg3 format:(id)arg4;

@end

