//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBAdPerformanceMetrics : NSObject
{
}

+ (CDStruct_4bcfbbae)freeAndTotalDiskBytes;
+ (unsigned long long)freeDiskBytes;
+ (unsigned long long)virtualMemoryBytes;
+ (unsigned long long)residentMemoryBytes;
+ (unsigned long long)totalMemoryBytes;
+ (unsigned long long)freeMemoryBytes;
+ (struct FBAdDeviceBatteryInfo)batteryInfo;
+ (unsigned int)coreCount;

@end

