//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBNAssetContentCache, NSMutableDictionary;

@interface FBNAssetsController : NSObject
{
    NSMutableDictionary *_assetControllers;
    FBNAssetContentCache *_contentCache;
}

@property(readonly, nonatomic) FBNAssetContentCache *contentCache; // @synthesize contentCache=_contentCache;
@property(readonly, nonatomic) NSMutableDictionary *assetControllers; // @synthesize assetControllers=_assetControllers;
- (void).cxx_destruct;
- (id)_assetContentURLsFromCollection:(id)arg1;
- (id)_assetContentURLsFromCardPayload:(struct NSDictionary *)arg1;
- (_Bool)hasCachedContentForCardPayload:(struct NSDictionary *)arg1;
- (void)clearAssetContentCacheForCardPayload:(struct NSDictionary *)arg1;
- (void)cacheAssetContentForCardPayload:(struct NSDictionary *)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_assetContentURLsFromAssetDictionary:(id)arg1;
- (id)_assetTypeFromDictionary:(id)arg1;
- (id)viewForAsset:(id)arg1;
- (id)assetFromDictionary:(id)arg1;
- (id)assetControllerForAssetType:(id)arg1;
- (void)registerAssetController:(id)arg1 forAssetType:(id)arg2;
- (id)init;

@end

