//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString, UIColor, UIFont;

@interface FBNCardTextContent : NSObject
{
    UIFont *_font;
    UIColor *_textColor;
    long long _textAlignment;
    NSAttributedString *_attributedText;
}

+ (id)contentFromDictionary:(id)arg1;
@property(readonly, copy, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
@property(readonly, nonatomic) long long textAlignment; // @synthesize textAlignment=_textAlignment;
@property(readonly, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(readonly, nonatomic) UIFont *font; // @synthesize font=_font;
- (void).cxx_destruct;
- (id)initFromDictionary:(id)arg1;

@end

