//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;
@protocol FBNAsset;

@interface FBNCardActionsConfiguration : NSObject
{
    unsigned long long _style;
    unsigned long long _layoutStyle;
    id <FBNAsset> _background;
    double _height;
    double _topInset;
    double _contentInset;
    double _cornerRadius;
    NSArray *_actions;
}

+ (id)configurationFromDictionary:(id)arg1 assetsController:(id)arg2;
@property(readonly, copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(readonly, nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(readonly, nonatomic) double contentInset; // @synthesize contentInset=_contentInset;
@property(readonly, nonatomic) double topInset; // @synthesize topInset=_topInset;
@property(readonly, nonatomic) double height; // @synthesize height=_height;
@property(readonly, nonatomic) id <FBNAsset> background; // @synthesize background=_background;
@property(readonly, nonatomic) unsigned long long layoutStyle; // @synthesize layoutStyle=_layoutStyle;
@property(readonly, nonatomic) unsigned long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (id)initFromDictionary:(id)arg1 assetsController:(id)arg2;

@end

