//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBNCardAppEventsLogger : NSObject
{
}

+ (id)_appEventNameForButtonAction:(unsigned long long)arg1;
+ (void)_logAppEventWithName:(id)arg1 campaignIdentifier:(id)arg2;
+ (void)logButtonAction:(unsigned long long)arg1 forCardWithCampaignIdentifier:(id)arg2;
+ (void)logCardOpenWithCampaignIdentifier:(id)arg1;
+ (id)campaignIdentifierFromRemoteNotificationPayload:(id)arg1;

@end

