//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBNCardTextContent, NSURL, UIColor;

@interface FBNCardActionConfiguration : NSObject
{
    UIColor *_backgroundColor;
    UIColor *_borderColor;
    double _borderWidth;
    FBNCardTextContent *_content;
    NSURL *_actionURL;
}

+ (id)configurationFromDictionary:(id)arg1;
@property(readonly, nonatomic) NSURL *actionURL; // @synthesize actionURL=_actionURL;
@property(readonly, nonatomic) FBNCardTextContent *content; // @synthesize content=_content;
@property(readonly, nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(readonly, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(readonly, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (id)initFromDictionary:(id)arg1;

@end

