//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FBNCardActionsViewDelegate-Protocol.h"

@class FBNAssetsController, FBNCardActionsView, FBNCardBodyView, FBNCardConfiguration, FBNCardDismissButton, FBNCardHeroView, NSDictionary, NSString, UIActivityIndicatorView, UIView;
@protocol FBNCardViewControllerDelegate;

@interface FBNCardViewController : UIViewController <FBNCardActionsViewDelegate>
{
    id <FBNCardViewControllerDelegate> _delegate;
    NSString *_campaignIdentifier;
    FBNAssetsController *_assetsController;
    FBNCardConfiguration *_configuration;
    UIView *_contentView;
    UIActivityIndicatorView *_loadingIndicatorView;
    FBNCardHeroView *_heroView;
    FBNCardBodyView *_bodyView;
    FBNCardActionsView *_actionsView;
    FBNCardDismissButton *_dismissButton;
    struct NSDictionary *_payload;
}

@property(readonly, copy, nonatomic) NSDictionary *payload; // @synthesize payload=_payload;
@property(retain, nonatomic) FBNCardDismissButton *dismissButton; // @synthesize dismissButton=_dismissButton;
@property(retain, nonatomic) FBNCardActionsView *actionsView; // @synthesize actionsView=_actionsView;
@property(retain, nonatomic) FBNCardBodyView *bodyView; // @synthesize bodyView=_bodyView;
@property(retain, nonatomic) FBNCardHeroView *heroView; // @synthesize heroView=_heroView;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicatorView; // @synthesize loadingIndicatorView=_loadingIndicatorView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) FBNCardConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) FBNAssetsController *assetsController; // @synthesize assetsController=_assetsController;
@property(readonly, copy, nonatomic) NSString *campaignIdentifier; // @synthesize campaignIdentifier=_campaignIdentifier;
@property(nonatomic) __weak id <FBNCardViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_dismissButtonAction;
- (void)actionsView:(id)arg1 didPerformButtonAction:(unsigned long long)arg2 withOpenURL:(id)arg3;
- (void)_dismissFromButtonAction:(unsigned long long)arg1 withOpenURL:(id)arg2;
- (void)_logPushOpen;
- (void)_applicationWillEnterForeground;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (void)_reloadDismissButton;
- (void)_reloadContentViews;
- (void)_reloadSubviews;
- (void)_reloadConfiguration;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithPushCardPayload:(struct NSDictionary *)arg1 campaignIdentifier:(id)arg2 assetsController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

