//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBNCardActionsConfiguration, NSArray;
@protocol FBNCardActionsViewDelegate;

@interface FBNCardActionsView : UIView
{
    id <FBNCardActionsViewDelegate> _delegate;
    FBNCardActionsConfiguration *_configuration;
    UIView *_backgroundView;
    NSArray *_actionButtons;
}

@property(readonly, copy, nonatomic) NSArray *actionButtons; // @synthesize actionButtons=_actionButtons;
@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) FBNCardActionsConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) __weak id <FBNCardActionsViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_buttonAction:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithConfiguration:(id)arg1 assetsController:(id)arg2 delegate:(id)arg3;

@end

