//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIColor;

@interface FBNCardDismissButton : UIButton
{
    UIColor *_imageColor;
}

+ (id)_imageWithColor:(id)arg1;
@property(retain, nonatomic) UIColor *imageColor; // @synthesize imageColor=_imageColor;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

