//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class FBNCardActionConfiguration;

@interface FBNCardActionButton : UIButton
{
    FBNCardActionConfiguration *_configuration;
    unsigned long long _action;
}

+ (id)buttonFromConfiguration:(id)arg1 withCornerRadius:(double)arg2 action:(unsigned long long)arg3;
@property(readonly, nonatomic) unsigned long long action; // @synthesize action=_action;
@property(readonly, nonatomic) FBNCardActionConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (id)initWithConfiguration:(id)arg1 cornerRadius:(double)arg2 action:(unsigned long long)arg3;

@end

