//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBNAssetController-Protocol.h"

@class NSString;

@interface FBNImageAssetController : NSObject <FBNAssetController>
{
}

- (id)viewForAsset:(id)arg1;
- (_Bool)isValidAssetDictionary:(id)arg1;
- (id)cacheURLsForAssetDictionary:(id)arg1;
- (id)assetFromDictionary:(id)arg1 contentCache:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

