//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSMutableDictionary, NSString;

@interface FBSDKLikeActionControllerCache : NSObject <NSSecureCoding>
{
    NSString *_accessTokenString;
    NSMutableDictionary *_items;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, copy, nonatomic) NSString *accessTokenString; // @synthesize accessTokenString=_accessTokenString;
- (void).cxx_destruct;
- (void)_prune;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (void)resetForAccessTokenString:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithAccessTokenString:(id)arg1;

@end

