//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FBSDKMessengerContext.h"

@class NSSet, NSString;

@interface FBSDKMessengerURLHandlerReplyContext : FBSDKMessengerContext
{
    NSString *_metadata;
    NSSet *_userIDs;
}

@property(readonly, copy, nonatomic) NSSet *userIDs; // @synthesize userIDs=_userIDs;
@property(readonly, copy, nonatomic) NSString *metadata; // @synthesize metadata=_metadata;
- (void).cxx_destruct;
- (id)queryComponents;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithMetadata:(id)arg1 userIDs:(id)arg2;

@end

