//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBSDKAccessTokenCaching-Protocol.h"

@class FBSDKKeychainStoreViaBundleID, NSString;

@interface FBSDKAccessTokenCacheV3_17 : NSObject <FBSDKAccessTokenCaching>
{
    FBSDKKeychainStoreViaBundleID *_keychainStore;
}

- (void).cxx_destruct;
- (void)cacheAccessToken:(id)arg1;
- (void)clearCache;
- (id)fetchAccessToken;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

