//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBSDKUtility : NSObject
{
}

+ (id)URLEncode:(id)arg1;
+ (id)URLDecode:(id)arg1;
+ (id)queryStringWithDictionary:(id)arg1 error:(id *)arg2;
+ (id)dictionaryWithQueryString:(id)arg1;
- (id)init;

@end

