//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBSDKDynamicFrameworkLoader : NSObject
{
}

+ (void *)loadkSecClass;
+ (void *)loadkSecReturnData;
+ (void *)loadkSecMatchLimit;
+ (void *)loadkSecMatchLimitOne;
+ (void *)loadkSecAttrAccessGroup;
+ (void *)loadkSecClassGenericPassword;
+ (void *)loadkSecValueData;
+ (void *)loadkSecAttrGeneric;
+ (void *)loadkSecAttrService;
+ (void *)loadkSecAttrAccount;
+ (void *)loadkSecAttrAccessibleAfterFirstUnlockThisDeviceOnly;
+ (void *)loadkSecAttrAccessible;
+ (struct __SecRandom *)loadkSecRandomDefault;
- (id)init;

@end

