//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBSwizzle : NSObject
{
    _Bool _instance;
    Class _cls;
    SEL _selector;
    SEL _mangledSelector;
    struct objc_method *_method;
    struct objc_method *_mangledMethod;
    unsigned long long _ID;
}

@property(nonatomic) _Bool instance; // @synthesize instance=_instance;
@property(nonatomic) unsigned long long ID; // @synthesize ID=_ID;
@property(nonatomic) struct objc_method *mangledMethod; // @synthesize mangledMethod=_mangledMethod;
@property(nonatomic) struct objc_method *method; // @synthesize method=_method;
@property(nonatomic) SEL mangledSelector; // @synthesize mangledSelector=_mangledSelector;
@property(nonatomic) SEL selector; // @synthesize selector=_selector;
@property(retain, nonatomic) Class cls; // @synthesize cls=_cls;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithClass:(Class)arg1 selector:(SEL)arg2;

@end

