//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FFacebookHelper : NSObject
{
    struct TMulticastDelegate<void, FBSDKAccessToken *, FBSDKAccessToken *> _OnFacebookTokenChange;
    struct TMulticastDelegate<void> _OnFacebookUserIdChange;
    struct TMulticastDelegate<void, FBSDKProfile *, FBSDKProfile *> _OnFacebookProfileChange;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)profileChangeCallback:(id)arg1;
- (void)userIdChangeCallback:(id)arg1;
- (void)tokenChangeCallback:(id)arg1;
- (struct FDelegateHandle)AddOnFacebookProfileChange:(const TBaseDelegate_fa0f8b1c *)arg1;
- (struct FDelegateHandle)AddOnFacebookUserIdChange:(const TBaseDelegate_0445fc9b *)arg1;
- (struct FDelegateHandle)AddOnFacebookTokenChange:(const TBaseDelegate_87e0e685 *)arg1;
- (id)init;

@end

