//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "GIDSignInDelegate-Protocol.h"
#import "GIDSignInUIDelegate-Protocol.h"

@class NSString;

@interface FGoogleHelper : NSObject <GIDSignInDelegate, GIDSignInUIDelegate>
{
    struct TMulticastDelegate<void, const FGoogleSignInData &> _OnSignInComplete;
    struct TMulticastDelegate<void, const FGoogleSignOutData &> _OnSignOutComplete;
    struct TMulticastDelegate<void, const FGoogleSignOutData &> _OnDisconnectComplete;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)printAuthStatus;
- (void)signIn:(id)arg1 dismissViewController:(id)arg2;
- (void)signIn:(id)arg1 presentViewController:(id)arg2;
- (void)signInWillDispatch:(id)arg1 error:(id)arg2;
- (void)signIn:(id)arg1 didDisconnectWithUser:(id)arg2 withError:(id)arg3;
- (void)signIn:(id)arg1 didSignInForUser:(id)arg2 withError:(id)arg3;
- (void)logout;
- (void)login:(id)arg1;
- (struct FDelegateHandle)AddOnGoogleDisconnectComplete:(const TBaseDelegate_6a035cb8 *)arg1;
- (struct FDelegateHandle)AddOnGoogleSignOutComplete:(const TBaseDelegate_6a035cb8 *)arg1;
- (struct FDelegateHandle)AddOnGoogleSignInComplete:(const TBaseDelegate_706c73d2 *)arg1;
- (id)initwithClientId:(id)arg1 withBasicProfile:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

