//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FIOSAsyncTask : NSObject
{
    int bIsReadyForGameThread;
    id UserData;
    CDUnknownBlockType GameThreadCallback;
}

+ (void)ProcessAsyncTasks;
+ (void)CreateTaskWithBlock:(CDUnknownBlockType)arg1;
+ (void)initialize;
@property(copy) CDUnknownBlockType GameThreadCallback; // @synthesize GameThreadCallback;
@property(retain) id UserData; // @synthesize UserData;
- (void)dealloc;
- (_Bool)CheckForCompletion;
- (void)FinishedTask;
- (id)init;

@end

