//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FApplePlatformObject.h"

@class NSHashTable;

@interface FMetalDebugCommandEncoder : FApplePlatformObject
{
    NSHashTable *UpdatedFences;
    NSHashTable *WaitingFences;
}

+ (id)alloc;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (CDStruct_eb6fb79d *)classAllocator;
- (void)addWaitFence:(id)arg1;
- (void)addUpdateFence:(id)arg1;
- (id)commandEncoder;
- (void)dealloc;
- (id)init;

@end

