//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FNFPlayerAudioEngine-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface FNFAudioQueue : NSObject <FNFPlayerAudioEngine>
{
    struct OpaqueAudioQueue *_audioQueue;
    CDUnknownBlockType _putDataCallback;
    CDUnknownBlockType _errorCallback;
    struct AudioStreamBasicDescription _asbd;
    unsigned int _sampleFrameSize;
    struct AQBufferParameters _bufferParams;
    struct AudioTimeStamp _zeroTimestamp;
    struct OpaqueAudioQueueTimeline *_timeline;
    unsigned long long _state;
    _Bool _hasNoMoreFramesToEnqueue;
    struct AQBufferState _audioQueueBuffer[3];
    int _activeBufferIndex;
    unsigned long long _framesEnqueued;
    unsigned long long _buffersReturned;
    unsigned long long _enqueueDataCalls;
    NSObject<OS_dispatch_queue> *_internalQueue;
    float _pendingVolume;
    float _pendingVolumeRampTime;
}

+ (struct AQBufferParameters)_calculateBufferSizeAndPacketCountWithAsbd:(struct AudioStreamBasicDescription)arg1 frameSize:(unsigned int)arg2;
- (void).cxx_destruct;
- (void)_readDataIntoBuffer;
- (int)_startQueue;
- (void)_removeAudioQueue;
- (void)_stopAudio;
- (_Bool)_createAudioQueue;
- (int)_queueState;
- (CDStruct_1b6d18a9)getCurrentTime;
- (void)audioQueueOutputCallback:(struct OpaqueAudioQueue *)arg1 inBuffer:(struct AudioQueueBuffer *)arg2;
- (void)audioQueueErrorCallback:(struct OpaqueAudioQueue *)arg1;
- (void)audioQueueIsRunningCallback:(struct OpaqueAudioQueue *)arg1;
- (void)setVolume:(float)arg1 rampTime:(float)arg2;
- (void)resumeEnqueuingData;
- (void)stopLoadingData;
- (void)invalidate;
- (void)reset;
- (void)stop;
- (void)pause;
- (void)playWithStartTime:(CDStruct_1b6d18a9)arg1;
- (void)prepareToPlay;
- (void)dealloc;
- (void)setAudioStreamBasicDescription:(struct AudioStreamBasicDescription)arg1 extraParameters:(id)arg2 putDataCallback:(CDUnknownBlockType)arg3 errorCallback:(CDUnknownBlockType)arg4 sampleFrameSize:(unsigned int)arg5;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

