//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol FNFBandwidthProvider;

@interface FNFAdaptiveBitrateSelector : NSObject
{
    long long _type;
    long long _filter;
    double _fractionOfAvailableBandwidthToUse;
    id <FNFBandwidthProvider> _bandwidthProvider;
    double _screenWidth;
    double _screenHeight;
}

- (void).cxx_destruct;
- (void)_forTestingOverrideScreenWidth:(double)arg1 height:(double)arg2;
- (id)selectVideoTrackFromList:(id)arg1;
- (id)initWithSelectorType:(long long)arg1 filter:(long long)arg2 parameters:(struct FNFAbrParameters)arg3 bandwidthProvider:(id)arg4;
- (id)description;
- (id)init;

@end

