//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface FNFDashPlaylistData : NSObject
{
    _Bool _containsAudioTrack;
    _Bool _isLive;
    _Bool _isFragmented;
    NSArray *_timelineEntries;
    CDStruct_1b6d18a9 _playlistDuration;
}

@property(nonatomic) _Bool isFragmented; // @synthesize isFragmented=_isFragmented;
@property(nonatomic) _Bool isLive; // @synthesize isLive=_isLive;
@property(nonatomic) _Bool containsAudioTrack; // @synthesize containsAudioTrack=_containsAudioTrack;
@property(copy, nonatomic) NSArray *timelineEntries; // @synthesize timelineEntries=_timelineEntries;
@property(nonatomic) CDStruct_1b6d18a9 playlistDuration; // @synthesize playlistDuration=_playlistDuration;
- (void).cxx_destruct;
- (id)init;

@end

