//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FNFDataLoader-Protocol.h"

@class FNFAdaptiveBitrateSelector, FNFAssetResourceLoader, FNFAssetResourceLoadingRequest, FNFDashPlaylistData, FNFDataBlockDistributor, NSData, NSMutableArray, NSString, NSURL;
@protocol FNFDataLoaderDelegate, FNFTimer, FNFTimerManager, OS_dispatch_queue;

@interface FNFDashDataLoader : NSObject <FNFDataLoader>
{
    id <FNFDataLoaderDelegate> _delegate;
    FNFAssetResourceLoader *_resourceLoader;
    FNFDataBlockDistributor *_dataBlockDistributors[2];
    id <FNFTimerManager> _timerMananger;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSURL *_mpdURL;
    NSData *_mpdData;
    NSData *_initialMpdData;
    FNFAssetResourceLoadingRequest *_currentResourceLoaderRequests[2];
    FNFAssetResourceLoadingRequest *_currentResourceLoaderRequestForPlaylist;
    struct FNFTrackDownloaderState _downloadTrackers[2];
    _Bool _fullyLoaded[2];
    unsigned long long _bitrates[2];
    NSString *_representationId;
    NSString *_qualityLabel;
    NSString *_audioChannelConfiguration;
    int _urlIndex[2];
    _Bool _segmented;
    NSMutableArray *_segmentedURLs[2];
    NSURL *_segmentedInitURLs[2];
    _Bool _fetchedInitURL[2];
    NSURL *_cachedSegmentURLs[2];
    _Bool _dynamic;
    _Bool _live;
    NSString *_encodedInitData[2];
    id <FNFTimer> _playlistRefreshTimer;
    FNFDashPlaylistData *_playlistData;
    int _consecutiveStaleUpdates;
    int _consecutiveStaleUpdatesThreshold;
    int _segmentsFromEndToStart;
    NSURL *_fragmentedURLs[2];
    unsigned long long _fileSizes[2];
    unsigned long long _fragmentedInitializationLengths[2];
    int _indexToFetchTo;
    _Bool _parsedPlaylist;
    _Bool _prefetchFirstDataSegment;
    FNFAdaptiveBitrateSelector *_abrSelector;
    _Bool _useInlineInitSegments;
    _Bool _async;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_forTestingMakeSynchronous;
- (void)_forTestingOverrideTimerManager:(id)arg1;
- (void)_forTestingOverrideResourceLoader:(id)arg1;
- (int)indexToFetchTo;
- (int)segmentedCurrentRequestOffsetForTrack:(long long)arg1;
- (id)allSegmentedUrlsForTrack:(long long)arg1;
- (id)segmentedUrlForTrack:(long long)arg1;
- (id)segmentedInitUrlForTrack:(long long)arg1;
- (void)_dataFinished:(id)arg1 dataRequest:(id)arg2 contentInfo:(id)arg3 loadingRequest:(id)arg4 track:(long long)arg5;
- (void)_dataCallback:(id)arg1 offset:(unsigned long long)arg2 dataRequest:(id)arg3 track:(long long)arg4;
- (void)_prefetchSegmentedUrlRequest:(id)arg1;
- (void)_fetchUrlRequest:(id)arg1 offset:(unsigned long long)arg2 length:(unsigned long long)arg3 track:(long long)arg4;
- (void)_fetchNextFragmentedRangeAtOffset:(unsigned long long)arg1 length:(unsigned long long)arg2 track:(long long)arg3;
- (void)_handleInlineInitSegmentForTrack:(long long)arg1;
- (void)_fetchNextSegmentForTrack:(long long)arg1;
- (void)_handleMpdData:(id)arg1;
- (void)_playlistLoadingRequestCallback:(id)arg1 error:(id)arg2;
- (void)_updatePlaylist;
- (void)_cancelPlaylistTimer;
- (id)audioChannelConfiguration;
- (id)resourceLoader;
- (id)representationId;
- (id)debugDetails;
- (id)playlistData;
- (_Bool)live;
- (_Bool)isFullyDownloaded:(long long)arg1;
- (_Bool)isStreamDry;
- (unsigned long long)currentReceiveOffsetForTrack:(long long)arg1;
- (_Bool)fetchInProgressForTrack:(long long)arg1;
- (_Bool)isSegmented;
- (_Bool)isFragmented;
- (_Bool)isDash;
- (void)resume;
- (void)pause;
- (void)cancelRequests;
- (void)resetWithNewVideoDataBlockDistributor:(id)arg1 audioDataBlockDistributor:(id)arg2;
- (void)seekForwardToOffset:(unsigned long long)arg1 forTrack:(long long)arg2;
- (void)fetchToOffset:(unsigned long long)arg1 forTrack:(long long)arg2;
- (void)fetchFirstRequestForSeconds:(unsigned int)arg1 initializationAtomSize:(unsigned long long)arg2 track:(long long)arg3;
- (void)setDelegate:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithMpdUrl:(id)arg1 mpdData:(id)arg2 videoDataBlockDistributor:(id)arg3 audioDataBlockDistributor:(id)arg4 abrSelector:(id)arg5 segmentsFromEndToStart:(int)arg6 staleMpdUpdatesThreshold:(int)arg7 prefetchFirstDataSegment:(_Bool)arg8 useInlineInitSegments:(_Bool)arg9;

@end

