//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface FNFLiveDashAssetPrefetcher : NSObject
{
    NSMutableDictionary *_assets;
    NSMutableDictionary *_timers;
    struct mutex _mutex;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)prefetchURL:(id)arg1 timeManager:(id)arg2 delayBeforeDeallocInMs:(unsigned int)arg3 creatorBlock:(CDUnknownBlockType)arg4;
- (void)_releaseAssetWithUrlIfUnused:(id)arg1;
- (id)newAssetForURL:(id)arg1 creatorBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

