//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FStoreKitHelper.h"

@class NSMutableSet;

@interface FStoreKitHelperV2 : FStoreKitHelper
{
    TMulticastDelegate_22137c99 _OnProductRequestResponse;
    TMulticastDelegate_2b2adb1e _OnTransactionCompleteResponse;
    TMulticastDelegate_12b8021a _OnTransactionRestored;
    TMulticastDelegate_dad13ae6 _OnRestoreTransactionsComplete;
    TMulticastDelegate_12b8021a _OnTransactionPurchaseInProgress;
    TMulticastDelegate_12b8021a _OnTransactionDeferred;
    NSMutableSet *_PendingTransactions;
}

@property(retain, nonatomic) NSMutableSet *PendingTransactions; // @synthesize PendingTransactions=_PendingTransactions;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct FDelegateHandle)AddOnTransactionDeferred:(const TBaseDelegate_af776a3a *)arg1;
- (TMulticastDelegate_12b8021a *)OnTransactionDeferred;
- (struct FDelegateHandle)AddOnPurchaseInProgress:(const TBaseDelegate_af776a3a *)arg1;
- (TMulticastDelegate_12b8021a *)OnTransactionPurchaseInProgress;
- (struct FDelegateHandle)AddOnRestoreTransactionsComplete:(const TBaseDelegate_e7e2b5bd *)arg1;
- (TMulticastDelegate_dad13ae6 *)OnRestoreTransactionsComplete;
- (struct FDelegateHandle)AddOnTransactionRestored:(const TBaseDelegate_af776a3a *)arg1;
- (TMulticastDelegate_12b8021a *)OnTransactionRestored;
- (struct FDelegateHandle)AddOnTransactionComplete:(const TBaseDelegate_42bf5e4a *)arg1;
- (TMulticastDelegate_2b2adb1e *)OnTransactionCompleteResponse;
- (struct FDelegateHandle)AddOnProductRequestResponse:(const TBaseDelegate_867a88d4 *)arg1;
- (TMulticastDelegate_22137c99 *)OnProductRequestResponse;
- (void)dumpAppReceipt;
- (void)finalizeTransaction:(const struct FString *)arg1;
- (void)purchaseDeferred:(id)arg1;
- (void)purchaseInProgress:(id)arg1;
- (void)restoreTransaction:(id)arg1;
- (void)failedTransaction:(id)arg1;
- (void)completeTransaction:(id)arg1;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)requestProductData:(id)arg1 WithDelegate:(const TBaseDelegate_6994a642 *)arg2;
- (void)makePurchase:(id)arg1 SimulateAskToBuy:(_Bool)arg2;
- (void)makePurchase:(id)arg1 WithUserId:(const struct FString *)arg2 SimulateAskToBuy:(_Bool)arg3;
- (void)paymentQueue:(id)arg1 restoreCompletedTransactionsFailedWithError:(id)arg2;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)arg1;
- (void)dealloc;
- (id)init;

@end

