//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface GSDK_OpenInChromeController : NSObject
{
}

+ (id)sharedInstance;
- (id)pasteboardContent;
- (int)openInChromePreference;
- (_Bool)openInChrome:(id)arg1 withCallbackURL:(id)arg2 createNewTab:(_Bool)arg3;
- (_Bool)openInChrome:(id)arg1;
- (_Bool)isChromeInstalled;

@end

