//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextRange.h>

@interface IndexedRange : UITextRange
{
    struct _NSRange _range;
}

+ (id)rangeWithNSRange:(struct _NSRange)arg1;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
- (_Bool)isEmpty;
- (id)end;
- (id)start;

@end

