//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jan  3 2018 14:07:36).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (FString_Extensions)
+ (id)stringWithFString:(const struct FString *)arg1;
+ (id)stringWithTCHARString:(const unsigned short *)arg1;
@end

